apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /volume1/SHARED/registry
    server: 10.0.0.6
    persistentVolumeReclaimPolicy: Recycle
